//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatPhong
    {
        public int ID { get; set; }
        public int IDKH { get; set; }
        public int IDPhong { get; set; }
        public Nullable<System.DateTime> NGAYDAT { get; set; }
        public Nullable<System.DateTime> NGAYTRA { get; set; }
        public Nullable<int> SONGAYO { get; set; }
        public Nullable<int> IDDVu { get; set; }
        public Nullable<int> IDU { get; set; }
    }
}
