//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DICHVU
    {
        public int IDDichVu { get; set; }
        public string TenDichVu { get; set; }
        public Nullable<double> DonGia { get; set; }
    }
}
