//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANG()
        {
            this.DATPHONGs = new HashSet<DATPHONG>();
            this.HOADONs = new HashSet<HOADON>();
        }
    
        public int IDKhachhang { get; set; }
        public string Tenkhachhang { get; set; }
        public string CCCD_CMND { get; set; }
<<<<<<< HEAD
        public bool Loaikhach { get; set; }
=======
        public Nullable<bool> Loaikhach { get; set; }
        public Nullable<int> IDphong { get; set; }
>>>>>>> 55918c785da78b08d9a14e8d143381dc98894200
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATPHONG> DATPHONGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
    }
}
