//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiPhong
    {
        public int IDLoaiPhong { get; set; }
        public string TenLoaiPhong { get; set; }
        public Nullable<double> Gia { get; set; }
    }
}
