//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        public int IDNhanvien { get; set; }
        public string Tennhanvien { get; set; }
        public string Chucvu { get; set; }
        public Nullable<int> Sodienthoai { get; set; }
    }
}
